### PR TITLE
Tentative IE11 user-agent detection

### PR DESCRIPTION
**Pull request by camilledalmeras**
For reference:

http://msdn.microsoft.com/fr-fr/library/ie/bg182625%28v=vs.85%29.aspx#uaString 

The changes should bring the additional benefit of simplifying a wee bit the detection of less ancient versions of IE, as from IE 8 on, all bear "Trident" in the user-agent string .

_**WARNING_*

This is still untested code!

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
what are you trying to accomplish exactly?  just a cleanup?

**Comment by camilledalmeras** [comment]
If I am not getting the issue wrong, the changes brought to IE11's user-agent string (no more "MSIE" to check against) make these patches necessary to have it served the *.ie6.cache.html files instead of the *.oldmoz.cache.html ones. The cleanup part only comes as a side effect.

Now, as IE11 claims it is more standards-compliant than thou, maybe it should be indeed fed the *.moz.cache.html files, but this is way over my head. Besides, I unfortunately have no way to test this unless I download and install the 5Go+ virtual machine image from Microsoft (shivers).

As I pasted the wrong URL, please refer to this one instead for information on user-agent changes in IE11:

http://msdn.microsoft.com/en-US/library/ie/bg182625%28v=vs.85%29.aspx#uaString

Thanks.

**Comment by anthonyrisinger** [comment]
ah ok i see; yeah ideally the IE6 designation would not be necessary for IE11... i'll look closer at this tonight and we'll go from there, but at first glance it look fine to me. thanks!

**Comment by camilledalmeras** [comment]
Update: after some light testing, it appears my app works on IE11 with either the ie6 or mozilla files. Trees in the kitchensink example, on the other hand, are missing when the browser gets served the ie6 version, yet function properly when fed the mozilla one. This is about the only difference I could spot, but my tests have not been thorough in the least for lack of appropriate hardware.

**Comment by anthonyrisinger** [comment]
since it seems the `moz` ones may prove more functional, we'll leave it there for now -- feel free to open another tix should this change.

thanks!

**Comment by camilledalmeras** [comment]
Apologies for the confusion, as my description of the issue and the proposed solution proved muddled. To clarify, IE11 currently incorrectly gets fed the "oldmoz" (note: "oldmoz", not "moz") file, on which it chokes; if it is forced to run either the "ie6" or "moz" ones, my app works as intended.

In my two proposed patches, I modified the detection logic to have IE11 fed the "ie6" files as a stopgap measure. It indeed would be better to have it served the "moz" files, but this would entail more user-agent sniffing rigmarole...

For now, could you apply these patches knowing this is a suboptimal solution, and wait until pre-IE11 versions are not in use anymore to just treat IE as Mozilla?

Thank you.

**Pull request closed without merging**
