### PR TITLE
Option: DialogBox as 3x3 table with GWT Styles

### PR DESCRIPTION
**Pull request by happyalu**
Creates a DialogBox with 3x3 table with
(0,1) -> caption
(1,1) -> widget

Other elements are empty DIVs, with GWT CSS classes that can be used for styling.

See: http://google-web-toolkit.googlecode.com/svn/javadoc/latest/com/google/gwt/user/client/ui/DialogBox.html

To use it, create with DialogBox(..., gwt_cells=True)

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
this appears to maintain the expected API if the `gwt_cells` params is **not** passed, yes? it looks alright to me, but in general i'm trying to keep the existing libs stable while we figure out how to make the jump to GWT 2.x or higher ...

is there a specific version the 3x3 stuff was added?  this widget is probably based on GWT 1.5-1.6 ... if the widget was changed to 3x3 in a specific version, i'd like the kwarg to reflect that, say `gwt17strict` or simply `gwt17`.

**Comment by happyalu** [comment]
It seems the 3x3 stuff was added in 1.5 http://google-web-toolkit.googlecode.com/svn/javadoc/1.5/com/google/gwt/user/client/ui/DialogBox.html

and the current one is based probably on 1.4 http://google-web-toolkit.googlecode.com/svn/javadoc/1.4/com/google/gwt/user/client/ui/DialogBox.html

I could change the gwt_cells parameter to gwt15. But if pyjs has a roadmap for GWT2.x jump, I guess this change could wait until then :) I had this code in my repo since I was using a stylesheet generated by http://gwt-theme-generator.appspot.com/ so thought I'll send a pull request :)

**Comment by anthonyrisinger** [comment]
nah, the road map is not that set in stone, i think this may be useful in the interim.

can you change the param to `gwt15`, `git commit --amend`, and `git push -f`?  then i'll go ahead and pull.

thanks @happyalu!

**Comment by happyalu** [comment]
@xtfxme Will do that. 

I was looking at the GWT sources, and am now wondering if these changes are the right things to do, or whether I should create, in the style of GWT, these files:

pyjamas.ui.DecoratorPanel (the thing that creates 3x3)
pyjamas.ui.DecoratedPopupPanel 
and then

GWT's DialogBox by default inherits from DecoratedPopupPanel, but we can let the current version stay as it is for stability and create a new thing called pyjamas.ui.DecoratedDialogBox. 

Let me know if doing this (or something else) is better, or whether I should just change the current commit keyword and edit the request.

@xtfxme Thanks!

**Comment by happyalu** [comment]
@xtfxme Changed the keyword arg.

**Comment by anthonyrisinger** [comment]
hi :-)

is this still current/relevant? or have you implemented something else?

if you give the thumbs up for "still needed", i'll go ahead and merge.  thanks!

**Comment by happyalu** [comment]
hi :-) 

I didn't implement anything else to this effect, and I think this is useful. (Well, I am using it :-P). Please merge if you think it's appropriate. Thanks!

**Comment by anthonyrisinger** [comment]
LGTM, save a few tweaks i'll make after the fact ... thanks!

**Pull request merged**
