### PR TITLE
modified example index template to be more visually appealing.

### PR DESCRIPTION
**Pull request by ghost**
modified example index template to be more visually appealing.

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
@earney, this looks great, thanks!

just 3 quick-to-fix items blocking merge:
- add yourself to CREDITS (i don't see your name/email in there)
- remove trailing whitespace from _examples/static/examples.css (5 lines)
- re-add the comments surrounding each example ... these are special comments that cut themselves out when the example is "enabled".  if example XYZ is not built for whatever reason, it will not show up in the index (commented out in HTML):
  
  <pre>diff --git a/examples/_examples/util.py b/examples/_examples/util.py
  index 35ec4ca..74b5bb2 100644
  --- a/examples/_examples/util.py
  +++ b/examples/_examples/util.py
  @@ -81,6 +81,7 @@ PACKAGE = {
  
  INDEX = {
     &#39;example&#39;: r&#39;&#39;&#39;
  +&lt;!-- start {name} {{example.{name}._comment_end}}
       &lt;tr&gt;{{example.{name}.demo1}}
  
           &lt;td rowspan=&quot;{{example.{name}.numdemos}}&quot;&gt;
  @@ -92,6 +93,7 @@ INDEX = {
           &lt;/td&gt;
       &lt;/tr&gt;
       {{example.{name}.demos}}
  +{{example.{name}._comment_start}} --&gt;
   &#39;&#39;&#39;,
   &#39;demo&#39;: r&#39;&#39;&#39;
       &lt;td&gt;&lt;a href=&quot;{target}.html&quot;&gt;{target}&lt;/a&gt;&lt;/td&gt;
  </pre>

... it looks like i broke CSS loading when i move to `__output__`.  changing the path to `.../_examples/[...]` works only when you load the index file directly ... behind a webserver that would fail.  this should be fixed by treating `_examples/static` like a public dir, and cp'ing to `__output__`.  you can fix if you like, but not required for this pull.

**Comment by anthonyrisinger** [comment]
heh, i actually just meant remove the _trailing_ white space :-) but this is fine too.  this whole process is still a little funky and i'll probably try to tweak a little once waf is in place, but this is definitely and improvement ... thanks!

**Comment by anthonyrisinger** [comment]
oh and thanks for taking care of the `_examples/static` -> `__output__/static`, much appreciated!

**Comment by ghost** [comment]
it was a pleasure.   I've noticed a few issues with some of the examples, so I might take a look at that next.

**Pull request merged**
