### PR TITLE
fix asteroids example (ImageLoader issue),  fix uitest example

### PR DESCRIPTION
**Pull request by ghost**
modified ImageLoad.py to include onImageLoad function, as well as fix various errors in uitests, to get it working, for some reason pyjs is using the wrong UnitTest class, (ie, scope issue).  I was able to figure this out by setting the UnitTest class name to UnitTest1 and referencing that in the *test.py files.  Also added a write_web function in write.py (in uitest example) since I was receiving a do_escape arguments error.  I believe this is also a scope issue, that will eventually need to be resolved.

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
hmm, the scoping bits are interesting. your changes look fine but i'd like to investigate that problem before pulling -- would prefer avoiding a temp change to `UnitTest1`, if possible.

**Comment by ghost** [comment]
Please do (investigate).  Maybe I'm overlooking something (very likely).  Let me know what you find. :)

**Comment by anthonyrisinger** [comment]
i'll investigate this in the next few days or merge by weeks end -- thanks @earney!

**Comment by ghost** [comment]
Thanks..  I appreciate it.  I've been looking at some of the failing test cases under examples/libtest, and trying to fix some of those.  All of these involve the internal coding of pyjs, so its a little more involved, but I'm slowly making progress of understanding it.  Hopefully soon, I'll be able to make some submissions.

Billy

**Comment by ghost** [comment]
Should I try to split this into 2 pulls?  One for the onImageLoad, and then another for the UnitTest issue?

**Comment by anthonyrisinger** [comment]
nah that's fine, could you open a new issue for that problem, then add a `TODO` to the spots that use `UnitTest1` with a link to the issue?

i'll go ahead and pull after that, and we'll figure that problem out another day.

**Comment by ghost** [comment]
okay.  I believe this is ready to be pulled.

**Comment by anthonyrisinger** [comment]
@earney, LGTM! thanks for being patient :-)

**Pull request merged**
