### PR TITLE
Directory restructure and full support for pip install and pip install -e (development mode)

### PR DESCRIPTION
**Pull request by sarvi**
This pull has the following
1. The directory restructuring and re-organization into 2 sub project directories pyjs-tools and pyjs-pyjamas
2. Now works with virtualenv python sandboxing.
3. full support for pip install and pip-install -e (development mode)
4. Some documentation file changes to describe the new install and development flow
5. a pip install requirements.txt to keep things simple 

ATTENTION Kees Bos: Can you please check if you examples restructuring is still fine and I have not screwed it up.
That was the one merge conflict I had to deal with, but was relatively simple.

### CODE REVIEW

**Comment by anthonyrisinger** [comment]
first off -- thanks for taking the time/energy to tackle some of this, much appreciated!

i don't think supporting pip development mode warrants this level of modification (exporting PYTHONPATH or similar is virtually identical), but good portions of your changes get us closer to a standard/normal python package structure, so we'll see where this goes... that said, this is a pretty massive change, so i just want to establish upfront **to everyone involved that we need to take our time here**... alas, it's like 5am and i have to work in 3 hrs so this will be brief, and i will add more later.

the biggest problem offhand is that throughout these edits `.gitignore` was not updated so there is a ton of stuff committed that should not be.  these will need to be rebased out, but you can simply remove them for now, and add another commit... i will help you clean it up before a final merge.

^^^ an example of the above is `pyjd/__init__.py`; this is an autogenerated file.

i'm pretty sure pyjd is totally borked, but i need to do a little legwork before i can verify this and/or offer solution, so it'll have to wait.

i don't want more references to `pyjamas`; aside from being a completely annoying/unprofessional title, it causes confusion with any other variants of this project, namely `pyj.be` (should that ever amount to anything). additionally, my `meta_path` work dynamically reroutes imports from `pyjamas` to `pyjs.ui`, so this would be better suited as `pyjs-ui`.

TBH, i don't like the non-importable top level dirs at all... `pyjs-tools` should just be `pyjs`, and `pyjs-pyjamas` should ideally be `pyjs/ui`... but IIRC this was the source of much of my problems in the past (the issues i vaguely referenced on the ML) so if that doesn't work it's OK for now (`pyjs-pyjamas` still needs a rename though)... FTW, there is a lot of path hackery going on, and at least 2-3 _different_ `pyjs` dirs are directly importable as `pyjs` at various times throughout the build process... yes, it's completely gross, but lower-level work is needed to correct, so it's OK to punt if need be.

`pyjswaddons` and `pyjswidgets` should move back to their original names as it's irrelevant to a restructuring and adds noise (it's critical a change like this include the **absolute minimum** needed to implement)

^^^ to reiterate: _anything that is not ABSOLUTELY necessary to support the restructure must be removed!_ (they can be added later by future pull request, if useful!)

more of a note to me: website/examples/API rebuilds all affected by this.

...i had several more that are escaping me now, so i'll need to revisit at a later time. apologies if some of it doesn't make sense -- address what you can and i can clarify anything as needed.

thanks @sarvi!

**Comment by sarvi** [comment]
A couple of responses.

My intent was a standard python package as much as being able pip install. Much of the python script generation, such as bootstrap.py and pyjd/**init**.py.in can now go away.

Can you let me know what part of .ignore needs updating? Except for pyjd/**init**.py which I will remove from .gitignore in my next commit as its not needed anymore. I have modified pyjd/**init**.py to make sure it works by itself without having to be generated.

pyjd may be borked because I have not been able to test it on a mac. But not because of the above as explained and I have kept the name pyjd instead of the pyjsd that I changed eariler. I tired running pyjd and it did not seem to have any path issues. Just that it couldn't find hulahop in my workspace. But do try and let me know.

Antony-"TBH, i don't like the non-importable top level dirs at all... pyjs-tools should just be pyjs, and pyjs-pyjamas should ideally be pyjs/ui... but IIRC this was the source of much of my problems in the past (the issues i vaguely referenced on the ML) so if that doesn't work it's OK for now (pyjs-pyjamas still needs a rename though)... FTW, there is a lot of path hackery going on, and at least 2-3 different pyjs dirs are directly importable as pyjs at various times throughout the build process... yes, it's completely gross, but lower-level work is needed to correct, so it's OK to punt if need be."

I can rename pyjs-pyjamas to pyjs-widgets. But the idea of the top level directories to allow these to be split into separate projects once this restructuring dust settles down. The more I look at this, these are very different beasts and pyjs-tools can be applicable as it evolves to many more problems that just the gwt widget sets that is pyjamas.
So far I haven't heard anyone say it must be together, just people wondering if it was worth the effort. Now that the effort has been put and things work and they are now easily separatable, is there anyone with a strong reason why we shouldn't split?? Also note, that this will in no way hamper simplicity as can be seen by the requirements.txt file or that when we do, simply have a to setup a dependency in the setup.py and things will get pulled and installed automatically. That said I am not going to argue the point further if more people prefer it a single project.

Also relating to the path hackery. I have done some fixing to it in my already pulled pip-install commit as well some more additional stuff in this diff which means that the build works with this new restructure and I was able to run all  the big examples I tried. So do tell me what isn't working after the restructure and I will fix.

pyjsaddons and pyjswidgets - If these are to be standard installable packages as they are no, the shouldn't have generic names like addons or library as they may get installed into the standard site-packages which I changed them. I can change them to pyjsaddons and pyjslibrary, but I wouldn't recommend leaving them as addons and library.

If I have missed something do let me know.

**Comment by eukreign** [comment]
I like the new layout. The two root project should be un-importable to make it clear that those are separate projects.

I think "pyjs-tools" will eventually become "pyjs" (replacing current pyjs repo) once it's split out into it's own project. I also think "pyjs-pyjamas" is a good name because it will be the legacy/snapshot of the current widget set.

Personally, I think given all of this effort why not take the next step and actually turn them into two separate projects.

@sarvi What do you think about actually splitting up pyjs-tools and pyjs-pyjamas into separate repos?

You can create the repos under your account and then once everything is working transfer them to the pyjs organization. Once pyjs-tools is fully working we can rename that to "pyjs" and move current "pyjs" to pyjs-legacy.

**Comment by anthonyrisinger** [comment]
i'll have to address your other comments tonight, but there was a reason it was generated -- pyjd can be installed systemwide in such a  way that the `__init__.py` files is separated from the library installation.  the assumption of `dirname(__file__)` is not always valid.  removing `bootstrap.py` means removing support for pyjd launchers for all platforms. by top level imports i means `pyjamas` itself is top-level, not `pyjswidgets.pyjamas`... i haven't had time to look but the only way this could possibly be working is because its being added to `sys.path` at some point, which is not an improvement over adding `library` to the `sys.path`. in the end -- even if not right now -- everything will be under a single `pyjs` namespace.

@eukreign the only way i'd consider `*-pyjamas` is if the library is 100% frozen, possibly maintenance, otherwise it's active devel... i literally cannot give a talk about this product without eliciting laughter from the group, so i'm not going to budge much here ;) `pyjs.oldui` or anything else would be orders of magnitude more professional... you know as well as i that image goes a long way.

i know everyone is excited, and it's really great to see a flurry of activity... but i haven't even looked at how the stuff _already_ merged impacts things (though i hope/presume Kees did to some degree) let alone reviewed this in enough detail to pull, and i don't want to have to undo/backtrack later on -- there is no need to merge this or anything else hastily -- we'll press forward and allow sufficient time to review.

**Comment by eukreign** [comment]
Given that it'll be legacy I don't really care that much what you call the old gwt stuff. Although even if you name it pyjs-pyjamas why would you ever have to mention it in presentations? GitHub orders repositories based on activity. If pyjs-pyjamas gets no activity it'll end up at the bottom of the list with pyjs and pyjs-_some new UI lib_ towards the top.

pyjamas is afterall the historical name for it, why not call it what it is?

**Comment by sarvi** [comment]
1. Ok, I am just realizing the it was the name pyjamas that is cause for concern.
   So how about pyjs-widgets or pyjs-gwt or something along those lines.
2. Right now everything can be installed system wide. So I am not sure I understand why pyjd cannot be installed system wide with my changes. And bin/pyjd should be correctly be script that gets installed by the setup.py.
   I can fix that.  
   But also note that the pyjd bash script is really NOT needed with the way its currently organized. as there is no PYTHONPATH variable that needs to be set. I was able to do myvirtpython/bin/python KitchenSink.py without any path issues atleast as far as it went.
3. As far how things got added to sys.path to make things, I didn't screw around with hacking too much of the internals of the compiler/build. Just enough during the import process to do this automatically and remove the need for such things as bootstrap.py and script generation is at best a a bit funky.

**Comment by eukreign** [comment]
From re-reading this thread it occurred to me that you haven't actually tested this under any desktop runtimes.

If all you have is a Mac can you install some virtual machine software and then install Linux to test pyjd?

**Comment by sarvi** [comment]
@xtfxme 
I can still combine pyjs-tools and pyjs-pyajams together into the root and simply combine their setup.py files
It would address your immediate concerns of not liking sub-directories but still keep it quickly separatable when yall decide to do it. Would you prefer that?

@eukreign 
Sorry. Don't have much space on my mac to do that kinda stuff. But if someone can show me how I can Pyjs-Desktop, I can certainly use that to test it on the desktop. @xtfxme  Any pointers :-)

**Comment by sarvi** [comment]
@xtfxme BTW, I really don't see anything wrong with the name pyjamas. If there is something political with the history you are trying to avoid. I can totally understand that and I have no problem avoiding it. But I don't get "i literally cannot give a talk about this product without eliciting laughter" though. People use pyjamas or don't based on whether it can help them do what they want, not because they like the name. I would say a healthy sense of humor is good when presenting to an audience, with a name like pyjamas you're already there, you don't need much advertising or a way to break ice :-D 
I also notice that if you really want to avoid the name pyjamas there is a lot of places in the code that will need changing a lot less worth it in my opinion.

On that note, Elon Musk has trade marked the following models for his upcoming cars. 
Model S(already out), Model E(due out in 4 years) Model X(due end of this year) and Model Y(no due date). Now thats a sense of humour :-)

My 2c

**Comment by sarvi** [comment]
Done flattening things out per Antony's suggestion. Kept the setup.py distributed to keep future simple.
Actually this better in favor when wanting to  split in the future, as splitting this into 2 repos will not require any moving of directories just removing the appropriate ones.
Have kept the setup.py values distributed across setup_pyjstools.py and setup_widgets.py to keep splitting simple

**Comment by anthonyrisinger** [comment]
awesome, thanks @sarvi!

this is looking pretty good, i hope to try it out tonight, along with pyjd stuff... if all goes well i'm hoping to merge this over the weekend.

**Comment by anthonyrisinger** [comment]
sorry i didnt get to this over the weekend; i was out of town and didn't even get a chance to turn on a computer, let alone accomplish anything useful...

my son is staying with his Nana for a week though, so i'll be able to review this in depth for sure tonight.

**Comment by anthonyrisinger** [comment]
ok, i got thru most of this, so i'll try to get it merged tonight; i need to get the pypi creds from the person who set it up.

**Comment by anthonyrisinger** [comment]
i couldnt get this to rebase properly in the time i had, so i'll try again tonight.. (need to change the commits to one commit)

**Comment by eukreign** [comment]
Making it one commit is definitely a good idea. Will make it easier to trace things back to this pull request in the future if necessary.

**Comment by sarvi** [comment]
I just pulled the latest and reapplied all the directory restructuring manually. So that is one big diff.
And did git push --force. So this should merge without any trouble and will be a consolidated diff
as requested

Just one other note. I remove "import dynamic" from code in pyjs/ directories. As this seems unnecessary and
causes a dependency on pyjswidgets, which shouldn't be there if we are separate them into projects. Thats the extra change from what was in my original pushs

**Pull request merged**
